version: '3.8'

services:
  app:
    build: .
    ports:
      - "5786:5786"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - mezon-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-eatery}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - mezon-network

  redis:
    image: redis:7-alpine
    command: >
      sh -c "redis-server --appendonly yes
             ${REDIS_PASSWORD:+ --requirepass ${REDIS_PASSWORD}}"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "${REDIS_PASSWORD:+-a}", "${REDIS_PASSWORD}", "PING" ]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - mezon-network

volumes:
  postgres_data:
  redis_data:


networks:
  mezon-network:
    driver: bridge
